version: '2.3'

services:

  mysql:
    image: mysql:5.7.21
    volumes:
      - ./app:/app
      - ./sqls:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zipkin
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1

  adminer:
    image: adminer:4.6.2-standalone
    restart: always
    ports:
      - 8080:8080
