version: '2.3'

services:

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=users

  pgweb:
    image: sosedoff/pgweb:0.9.12
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/usr/bin/pgweb", "--bind=0.0.0.0", "--listen=8081", "--url=postgres://postgres:password1@postgres:5432/users?sslmode=disable"]
